- name: Configure apt sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: "0644"
    owner: root
  when: ansible_distribution_release == "focal"
  notify: update apt cache
  tags:
    - apt

- name: Configure apt ubuntu.sources
  template:
    src: ubuntu.sources.j2
    dest: /etc/apt/sources.list.d/ubuntu.sources
    mode: "0644"
    owner: root
  when: ansible_distribution_release != "focal"
  notify: update apt cache
  tags:
    - apt

# Ensure apt cache is updated before proceeding, otherwise
# packages may fail to install.
- meta: flush_handlers
